services:
  treevis1:
    container_name: treevis1
    build: .
    ports:
      - "8081:8080"

  treevis2:
    container_name: treevis2
    build: .
    ports:
      - "8082:8080"

  treevis3:
    container_name: treevis3
    build: .
    ports:
      - "8083:8080"
